update-info:
  isTemplate: true
  isInitialized: false
  version:
    current:
      commit: 304bdfcde071cba89e7c38d1b41737e9bcadd805
      date: 2022-08-09 23:40:30 +0300
  updateFiles:
  - .autosetup.yaml
  - .github/generate-base-yaml-json.py
  - .github/modify-twin-yamls.py
  - .github/script-copy-index-html.sh
  - .github/script-yamls-to-jsons.sh
  - .github/setup-update.py
  - .github/update-twinbase.py
  - .github/update-twindocs.py
  - .github/workflows/file-modifier.yml
  - .github/workflows/override-with-yamls.yml
  - .gitignore
  - LICENSE
  - README.md
  - docs/README.md
  - docs/index.html
  - docs/index.json
  - docs/index.yaml
  - docs/new-twin/index.html
  - docs/new-twin/template.yaml
  - docs/static/dt-page.html
  - docs/static/index.html
  - docs/static/jsonview.bundle.css
  - docs/static/jsonview.bundle.js
  - requirements.txt
